from GameArea import GameArea
from tkinter import *


board = GameArea()
board.displayGameArea()
#board.switchTokenPosition(board.gamearea[0][1], board.gamearea[1][1])
#board.switchTokenPosition(board.gamearea[1][1], board.gamearea[0][1])
board.moveSquareToken(board.gamearea[0][1])
board.displayGameArea()
board.moveSquareToken(board.gamearea[0][0])
board.displayGameArea()
board.moveSquareToken(board.gamearea[1][0])
board.displayGameArea()
board.moveSquareToken(board.gamearea[2][0])
board.displayGameArea()
board.moveSquareToken(board.gamearea[2][1])
board.displayGameArea()
board.moveSquareToken(board.gamearea[2][2])
board.displayGameArea()
board.moveSquareToken(board.gamearea[1][2])
board.displayGameArea()
board.moveSquareToken(board.gamearea[0][2])
board.displayGameArea()
board.moveSquareToken(board.gamearea[0][1])
board.displayGameArea()
board.moveSquareToken(board.gamearea[1][1])
board.displayGameArea()

"""print(board.gamearea[0][0].pos_X,board.gamearea[0][0].pos_Y, board.gamearea[0][0].tile_id)
print(board.gamearea[1][0].pos_X,board.gamearea[1][0].pos_Y,board.gamearea[1][0].tile_id)
print(board.gamearea[2][0].pos_X,board.gamearea[2][0].pos_Y,board.gamearea[2][0].tile_id)
print(board.gamearea[0][1].pos_X,board.gamearea[0][1].pos_Y,board.gamearea[0][1].tile_id)
print(board.gamearea[1][1].pos_X,board.gamearea[1][1].pos_Y,board.gamearea[1][1].tile_id)
print(board.gamearea[2][1].pos_X,board.gamearea[2][1].pos_Y,board.gamearea[2][1].tile_id)
print(board.gamearea[0][2].pos_X,board.gamearea[0][2].pos_Y,board.gamearea[0][2].tile_id)
print(board.gamearea[1][2].pos_X,board.gamearea[1][2].pos_Y,board.gamearea[1][2].tile_id)
print(board.gamearea[2][2].pos_X,board.gamearea[2][2].pos_Y,board.gamearea[2][2].tile_id)"""